
WG_ID=wg0
WG_PREFIX=/etc/wireguard
WG_CONF=$WG_PREFIX/$WG_ID.conf
PRIV_KEY_FILE=$WG_PREFIX/privatekey
PUB_KEY_FILE=$WG_PREFIX/publickey
WG_PORT=51830

PG_DATABASE=wg
PG_USER=wg_admin
PG_PASS=1234
PG_PORT=5432
